### ISSUE TITLE
summary()

### ISSUE THREAD

**Issue by tobiasko** [protViz/specL#18]
`> AssayLib <- genSwathIonLib(data=SpecLib, data.fit=SpecLib.red)
normalizing RT ...
found 12 iRT peptide(s) in s:\p1007\Proteomics\TRIPLETOF_1\tobiasko_20150130\20150130_16_DDA_ctrl_2.wiff
building model ...
model with only one file.
generating ion library ...
start generating specLSet object ...
length of findNN idx  828
using BiocParallel::bpmapply( ...
length of genSwathIonLibSpecL   828
time taken:  1.5387909412384 secs
length of genSwathIonLibSpecL  after fragmentIonRange filtering 825
**> summary(AssayLib)
  Length    Class     Mode 
       1 specLSet       S4** 
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] specL_1.8.0          protViz_0.2.15       seqinr_3.3-3         RSQLite_1.1-1        DBI_0.5-1           
[6] BiocInstaller_1.24.0

loaded via a namespace (and not attached):
[1] parallel_3.3.2 tools_3.3.2    memoise_1.0.0  Rcpp_0.12.8    ade4_1.7-4     digest_0.6.10 

Summary() does not display the summary as described in the vignette.

**Comment by tobiasko** [comment]
`> protViz::summary(AssayLib)
Error: 'summary' is not an exported object from 'namespace:protViz'

**Comment by cpanse** [comment]
S4 reload problem
