### ISSUE TITLE
plot specLSet

### ISSUE THREAD

**Issue by wolski** [protViz/specL#22]
Uses iRTpeptides for visualization even if a different set of peptides was used for calibration.

setMethod(f="plot", signature="specLSet", 
          definition=function(x, iRTpeptides=specL::iRTpeptides, art=FALSE, ...){
            
            file <- as.factor(unlist( lapply(x@ionlibrary, function(y){ y@filename }) ))
            peptide <- unlist( lapply(x@ionlibrary, function(y){ y@peptide_sequence }) )
            
            .retentiontimePlot(x, file, peptide, iRTpeptides=iRTpeptides, ...)
            .retentiontimePlotFile(x, file, peptide, iRTpeptides=iRTpeptides, ...)

**Comment by cpanse** [comment]
solved with version 1.9.6

cp@sirius:~/__checkouts/R/specL/R > svn diff
Index: genSwathIonLib.R
===================================================================
--- genSwathIonLib.R	(revision 128824)
+++ genSwathIonLib.R	(working copy)
@@ -403,7 +403,8 @@
                                        ignoreMascotIonScore = ignoreMascotIonScore,
                                        topN = topN,
                                        fragmentIonMzRange = fragmentIonMzRange,
-                                       fragmentIonRange = fragmentIonRange),
+                                       fragmentIonRange = fragmentIonRange,
+                                       iRTpeptides=iRT),
                   rt.normalized=unlist(x.rt[output.filter]), 
                   rt.input=unlist(lapply(data, function(x){x$rt}))[output.filter])
          )
Index: specLSet.R
===================================================================
--- specLSet.R	(revision 128824)
+++ specLSet.R	(working copy)
@@ -187,7 +187,7 @@
 
 
 setMethod(f="plot", signature="specLSet", 
-          definition=function(x, iRTpeptides=specL::iRTpeptides, art=FALSE, ...){
+          definition=function(x, iRTpeptides=x@input.parameter$iRTpeptides, art=FALSE, ...){
             
             file <- as.factor(unlist( lapply(x@ionlibrary, function(y){ y@filename }) ))
             peptide <- unlist( lapply(x@ionlibrary, function(y){ y@peptide_sequence }) )
cp@sirius:~/__checkouts/R/specL/R >

**Comment by cpanse** [comment]
solved by adding the iRTs to the ionlibrary and changing default parameter. 
version 1.9.6 on bioc dev
